#cloud-config
coreos:
    units:

      - name: stop-reboot-manager.service
        content: |
          [Unit]
          Description=stop update-engine-reboot-manager

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/systemctl stop update-engine-reboot-manager.service
          ExecStartPost=/usr/bin/systemctl mask update-engine-reboot-manager.service

          [Install]
          WantedBy=multi-user.target

      - name: source.service
        command: start
        content: |
          [Unit]
          Description=Shared source directory from Vagrant
          Requires=docker.service
          Requires=mnt-source.mount

          [Service]
          Restart=no
          ExecStart=/usr/bin/docker run -v /mnt/source:/opt/source:rw --name SOURCE busybox true

      - name: devenv.service
        command: start
        content: |
          [Unit]
          Description=Copy in scripts dir into /home/core/bin and add /home/core/bin to path
          Requires=mnt-source.mount

          [Service]
          Restart=no
          ExecStart=/mnt/source/docker/scripts/copy-scripts.sh

      - name: sshkeys.service
        command: start
        content: |
          [Unit]
          Description=Ensure the ssh files are in the right spot for sshing into containers
          Requires=mnt-source.mount

          [Service]
          Restart=no
          ExecStart=/mnt/source/docker/scripts/setup-ssh.sh